name: ci_workflow

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: Launch docker compose
        run: |
          docker compose up --build -d
          sleep 10
      - name: Test train script with pytest
        id: pytest_train_api
        run: |
          docker compose run --workdir /app train-api python -m pytest -s -v test_train.py
          sleep 10
      
      - name: Test update script with pytest
        id: pytest_update_api
        run: |
          docker compose run --workdir /app update-api python -m pytest -s -v test_update.py
          sleep 10
      
      
      - name: Test predict script with pytest
        id: pytest_predict_api
        run: |
          docker compose run --workdir /app predict-api python -m pytest -s -v test_predict.py
          sleep 10

      - name: Test gateway script with pytest
        id: pytest_gateway_api
        run: |
          docker compose run --workdir /app gateway-api python -m pytest -s -v test_app.py
          sleep 10

      - name: Close docker compose
        run: |
          docker compose down
